import Banner from 'componemt/components/Banner';
import Header from 'componemt/components/Header';
import { Inter } from 'next/font/google';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <div>
      <Head>
        <title>Airanb</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://i.ibb.co/1RTSVhw/airanb-favicon.png" />
      </Head>
      <Header />
      <Banner />
    </div>
  );
}
